
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetsLibrary
{
	public partial class HorizontalWidgetsList
	{
		private global::Gtk.ScrolledWindow scrolledwindow2;
		private global::Gtk.HBox widgetList;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetsLibrary.HorizontalWidgetsList
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetsLibrary.HorizontalWidgetsList";
			// Container child WidgetsLibrary.HorizontalWidgetsList.Gtk.Container+ContainerChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.widgetList = new global::Gtk.HBox ();
			this.widgetList.Name = "widgetList";
			this.widgetList.Spacing = 6;
			w1.Add (this.widgetList);
			this.scrolledwindow2.Add (w1);
			this.Add (this.scrolledwindow2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
