
// This file has been generated by the GUI designer. Do not modify.
namespace WidgetsLibrary
{
	public partial class TestWidget
	{
		private global::Gtk.ScrolledWindow scrolledwindow2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Image image1;
		private global::Gtk.Image image2;
		private global::Gtk.Image image3;
		private global::Gtk.Image image6;
		private global::Gtk.Image image5;
		private global::Gtk.Image image4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WidgetsLibrary.TestWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WidgetsLibrary.TestWidget";
			// Container child WidgetsLibrary.TestWidget.Gtk.Container+ContainerChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(3));
			// Container child hbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.hbox1.Add (this.image1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.hbox1.Add (this.image2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.hbox1.Add (this.image3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image3]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.hbox1.Add (this.image6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image6]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.hbox1.Add (this.image5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image5]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image4 = new global::Gtk.Image ();
			this.image4.Name = "image4";
			this.hbox1.Add (this.image4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image4]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			w1.Add (this.hbox1);
			this.scrolledwindow2.Add (w1);
			this.Add (this.scrolledwindow2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
