
// This file has been generated by the GUI designer. Do not modify.
namespace GraphTool
{
	public partial class PlotWidgetList
	{
		private global::WidgetsLibrary.HorizontalWidgetsList horizontalwidgetslist1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GraphTool.PlotWidgetList
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GraphTool.PlotWidgetList";
			// Container child GraphTool.PlotWidgetList.Gtk.Container+ContainerChild
			this.horizontalwidgetslist1 = new global::WidgetsLibrary.HorizontalWidgetsList ();
			this.horizontalwidgetslist1.Events = ((global::Gdk.EventMask)(256));
			this.horizontalwidgetslist1.Name = "horizontalwidgetslist1";
			this.Add (this.horizontalwidgetslist1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
